#! /bin/bash
# scriptbc -- 계산의 결과를 리턴하는 'bc' 래퍼 스크립트

if [ "$1" = "-p" ] ; then
    precision=$2
    shift 2
else
    precision=2
    # 위는 기본값이 되어버렸다.
fi

bc -q -l << EOF
    scale=$precision
    $*
    quit
EOF

exit 0
